# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name DWDataReader
#' @title DWDataReader library class
#' @description Library to import data from DEWESoft data files (*.dxd, *.dxz)
NULL

